# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brokentelephone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='brokentelephone.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x62rokentelephone.proto\")\n\x16\x42rokenTelephoneRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x17\x42rokenTelephoneResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2V\n\x0f\x42rokenTelephone\x12\x43\n\x0cSaySomething\x12\x17.BrokenTelephoneRequest\x1a\x18.BrokenTelephoneResponse\"\x00\x62\x06proto3')
)




_BROKENTELEPHONEREQUEST = _descriptor.Descriptor(
  name='BrokenTelephoneRequest',
  full_name='BrokenTelephoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='BrokenTelephoneRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=66,
)


_BROKENTELEPHONERESPONSE = _descriptor.Descriptor(
  name='BrokenTelephoneResponse',
  full_name='BrokenTelephoneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='BrokenTelephoneResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['BrokenTelephoneRequest'] = _BROKENTELEPHONEREQUEST
DESCRIPTOR.message_types_by_name['BrokenTelephoneResponse'] = _BROKENTELEPHONERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BrokenTelephoneRequest = _reflection.GeneratedProtocolMessageType('BrokenTelephoneRequest', (_message.Message,), dict(
  DESCRIPTOR = _BROKENTELEPHONEREQUEST,
  __module__ = 'brokentelephone_pb2'
  # @@protoc_insertion_point(class_scope:BrokenTelephoneRequest)
  ))
_sym_db.RegisterMessage(BrokenTelephoneRequest)

BrokenTelephoneResponse = _reflection.GeneratedProtocolMessageType('BrokenTelephoneResponse', (_message.Message,), dict(
  DESCRIPTOR = _BROKENTELEPHONERESPONSE,
  __module__ = 'brokentelephone_pb2'
  # @@protoc_insertion_point(class_scope:BrokenTelephoneResponse)
  ))
_sym_db.RegisterMessage(BrokenTelephoneResponse)



_BROKENTELEPHONE = _descriptor.ServiceDescriptor(
  name='BrokenTelephone',
  full_name='BrokenTelephone',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=112,
  serialized_end=198,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaySomething',
    full_name='BrokenTelephone.SaySomething',
    index=0,
    containing_service=None,
    input_type=_BROKENTELEPHONEREQUEST,
    output_type=_BROKENTELEPHONERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BROKENTELEPHONE)

DESCRIPTOR.services_by_name['BrokenTelephone'] = _BROKENTELEPHONE

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class BrokenTelephoneStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SaySomething = channel.unary_unary(
          '/BrokenTelephone/SaySomething',
          request_serializer=BrokenTelephoneRequest.SerializeToString,
          response_deserializer=BrokenTelephoneResponse.FromString,
          )


  class BrokenTelephoneServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def SaySomething(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_BrokenTelephoneServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SaySomething': grpc.unary_unary_rpc_method_handler(
            servicer.SaySomething,
            request_deserializer=BrokenTelephoneRequest.FromString,
            response_serializer=BrokenTelephoneResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'BrokenTelephone', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaBrokenTelephoneServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SaySomething(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaBrokenTelephoneStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SaySomething(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SaySomething.future = None


  def beta_create_BrokenTelephone_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('BrokenTelephone', 'SaySomething'): BrokenTelephoneRequest.FromString,
    }
    response_serializers = {
      ('BrokenTelephone', 'SaySomething'): BrokenTelephoneResponse.SerializeToString,
    }
    method_implementations = {
      ('BrokenTelephone', 'SaySomething'): face_utilities.unary_unary_inline(servicer.SaySomething),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_BrokenTelephone_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('BrokenTelephone', 'SaySomething'): BrokenTelephoneRequest.SerializeToString,
    }
    response_deserializers = {
      ('BrokenTelephone', 'SaySomething'): BrokenTelephoneResponse.FromString,
    }
    cardinalities = {
      'SaySomething': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'BrokenTelephone', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
