# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import brokentelephone_pb2 as brokentelephone__pb2


class BrokenTelephoneStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SaySomething = channel.unary_unary(
        '/BrokenTelephone/SaySomething',
        request_serializer=brokentelephone__pb2.BrokenTelephoneRequest.SerializeToString,
        response_deserializer=brokentelephone__pb2.BrokenTelephoneResponse.FromString,
        )


class BrokenTelephoneServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SaySomething(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BrokenTelephoneServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SaySomething': grpc.unary_unary_rpc_method_handler(
          servicer.SaySomething,
          request_deserializer=brokentelephone__pb2.BrokenTelephoneRequest.FromString,
          response_serializer=brokentelephone__pb2.BrokenTelephoneResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'BrokenTelephone', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
