apiVersion: 1

deleteDatasources:
  - name: Jaeger
    orgId: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    uid: jaeger_datasource
    url: http://jaeger:16686
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: false
    version: 1
    editable: true
