receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug

processors:
  tail_sampling:
    decision_wait: 5s
    policies:
      [
        {
          name: probability,
          type: probabilistic,
          probabilistic: { sampling_percentage: 10 },
        },
        { name: slow, type: latency, latency: { threshold_ms: 1000 } },
      ]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [logging]
