receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug

processors:
  tail_sampling:
    decision_wait: 5s
    policies: [{ name: always, type: always_sample }]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [logging]
