receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    loglevel: debug
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, zipkin]
    metrics:
      receivers: [otlp]
      exporters: [logging]
    logs:
      receivers: [otlp]
      exporters: [logging]
