receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    loglevel: debug
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      exporters: [logging]
