receivers:
  otlp:
    protocols:
      grpc:
  hostmetrics:
    collection_intervals: 10s
    scrapers:
      memory:
      network:
exporters:
  logging:
    loglevel: debug
processors:
  batch:
    timeout: 10s
  attributes/add-location:
    actions:
      - key: location
        action: insert
        value: europe
  span/rename:
    name:
      from_attributes: [location, item, quantity]
      separator: ":"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes/add-location, span/rename]
      exporters: [logging]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
