receivers:
  otlp:
    protocols:
      grpc:
  jaeger:
    protocols:
      thrift_binary:
service:
  pipelines:
    traces/otlp:
      receivers: [otlp]
    traces/jaeger:
      receivers: [jaeger]
    traces/both:
      receivers: [otlp, jaeger]
