receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      load:
      memory:
      network:
  otlp:
    protocols:
      grpc:
  jaeger:
    protocols:
      thrift_binary:
processors:
  attributes/add-key:
    actions:
      - key: example-key
        action: insert
        value: first
  attributes/update-key:
    actions:
      - key: example-key
        action: update
        value: second
  attributes/copy-and-delete:
    actions:
      - key: new-key
        action: upsert
        from_attribute: old-key
      - key: old-key
        action: delete
  attributes/include-secret:
    include:
      services: ["super-secret", "secret"]
      match_type: strict
    actions:
      - key: secret-attr
        action: delete
  probabilistic_sampler:
    sampling_percentage: 20
    hash_seed: 12345
  resource:
    attributes:
      - key: deployment.environment
        value: staging
        action: upsert
      - key: container.runtime
        from_attribute: runtime
        action: insert
      - key: runtime
        action: delete
service:
  pipelines:
    traces/otlp:
      receivers: [otlp]
      processors: [attributes/include-secret, probabilistic_sampler, resource]
