receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      load:
      memory:
      network:
  otlp:
    protocols:
      grpc:
  jaeger:
    protocols:
      thrift_binary:
service:
  pipelines:
    traces/otlp:
      receivers: [otlp]
    traces/jaeger:
      receivers: [jaeger]
    traces/both:
      receivers: [otlp, jaeger]
    metrics:
      receivers: [hostmetrics]
