// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: brokentelephone.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrokenTelephoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BrokenTelephoneRequest) Reset() {
	*x = BrokenTelephoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brokentelephone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokenTelephoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokenTelephoneRequest) ProtoMessage() {}

func (x *BrokenTelephoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brokentelephone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokenTelephoneRequest.ProtoReflect.Descriptor instead.
func (*BrokenTelephoneRequest) Descriptor() ([]byte, []int) {
	return file_brokentelephone_proto_rawDescGZIP(), []int{0}
}

func (x *BrokenTelephoneRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BrokenTelephoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BrokenTelephoneResponse) Reset() {
	*x = BrokenTelephoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brokentelephone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokenTelephoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokenTelephoneResponse) ProtoMessage() {}

func (x *BrokenTelephoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brokentelephone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokenTelephoneResponse.ProtoReflect.Descriptor instead.
func (*BrokenTelephoneResponse) Descriptor() ([]byte, []int) {
	return file_brokentelephone_proto_rawDescGZIP(), []int{1}
}

func (x *BrokenTelephoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_brokentelephone_proto protoreflect.FileDescriptor

var file_brokentelephone_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x6e, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x16, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x6e, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x33, 0x0a, 0x17, 0x42,
	0x72, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0x56, 0x0a, 0x0f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x53, 0x61, 0x79, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x12, 0x17, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x42,
	0x72, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x6f, 0x74, 0x65, 0x6e,
	0x2f, 0x63, 0x6e, 0x6f, 0x62, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_brokentelephone_proto_rawDescOnce sync.Once
	file_brokentelephone_proto_rawDescData = file_brokentelephone_proto_rawDesc
)

func file_brokentelephone_proto_rawDescGZIP() []byte {
	file_brokentelephone_proto_rawDescOnce.Do(func() {
		file_brokentelephone_proto_rawDescData = protoimpl.X.CompressGZIP(file_brokentelephone_proto_rawDescData)
	})
	return file_brokentelephone_proto_rawDescData
}

var file_brokentelephone_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_brokentelephone_proto_goTypes = []interface{}{
	(*BrokenTelephoneRequest)(nil),  // 0: BrokenTelephoneRequest
	(*BrokenTelephoneResponse)(nil), // 1: BrokenTelephoneResponse
}
var file_brokentelephone_proto_depIdxs = []int32{
	0, // 0: BrokenTelephone.SaySomething:input_type -> BrokenTelephoneRequest
	1, // 1: BrokenTelephone.SaySomething:output_type -> BrokenTelephoneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brokentelephone_proto_init() }
func file_brokentelephone_proto_init() {
	if File_brokentelephone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_brokentelephone_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokenTelephoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brokentelephone_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokenTelephoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brokentelephone_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brokentelephone_proto_goTypes,
		DependencyIndexes: file_brokentelephone_proto_depIdxs,
		MessageInfos:      file_brokentelephone_proto_msgTypes,
	}.Build()
	File_brokentelephone_proto = out.File
	file_brokentelephone_proto_rawDesc = nil
	file_brokentelephone_proto_goTypes = nil
	file_brokentelephone_proto_depIdxs = nil
}
